global.ie = 
{
    namespace: 'immersiveengineering',
    rarities: {
        colors: {            
            Common:      'white',
            Uncommon:    'yellow',
            Rare:        'aqua',
            Epic:        'light_purple',
            Masterwork:  'gold',
        },
        weights: {
            Common:      16,
            Uncommon:     8,
            Rare:         4,
            Epic:         2,
            Masterwork:   1,
        }
    },
    shaders: {
        // Masterwork
        'glacis': 'Masterwork',
        'omnitool': 'Masterwork',
        // Epic
        'darkfire': 'Epic',
        'kindled': 'Epic',
        'twili': 'Epic',
        'usurper': 'Epic',
        // Rare
        'ancient': 'Rare',
        'erruption': 'Rare',
        'ikelos': 'Rare',
        'lususnaturae': 'Rare',
        'massfusion': 'Rare',
        'netherforged': 'Rare',
        'sponsor': 'Rare',
        'vaulttec': 'Rare',
        // Uncommon
        'chloris': 'Uncommon',
        'dominator': 'Uncommon',
        'dragonsbreath': 'Uncommon',
        'harrowed': 'Uncommon',
        'hollow': 'Uncommon',
        'matrix': 'Uncommon',
        'microshark': 'Uncommon',
        'radiant': 'Uncommon',
        'regal': 'Uncommon',
        'sharkface': 'Uncommon',
        'waaagh': 'Uncommon',
        'warbird': 'Uncommon',
        // Common
        'acepride': 'Common',
        'angelsthesis': 'Common',
        'argo': 'Common',
        'astartes': 'Common',
        'bipride': 'Common',
        'crescentrose': 'Common',
        'crimsonlotus': 'Common',
        'enbypride': 'Common',
        'exia': 'Common',
        'eyas': 'Common',
        'felix': 'Common',
        'fox': 'Common',
        'gaypride': 'Common',
        'hawk': 'Common',
        'lesbianpride': 'Common',
        'locus': 'Common',
        'magnum': 'Common',
        'milo': 'Common',
        'n7': 'Common',
        'normandy': 'Common',
        'phoenix': 'Common',
        'qrow': 'Common',
        'rosequartz': 'Common',
        'stormflower': 'Common',
        'sunstrike': 'Common',
        'sutherland': 'Common',
        'taken': 'Common',
        'transpride': 'Common',
        'trident': 'Common',
        'vanguard': 'Common',
    },
    prideShaders: [
        'transpride',
        'enbypride',
        'gaypride',
        'lesbianpride',
        'bipride',
        'acepride'
    ]
}