#Enables editing of recipes. When disabled CTGUI can still be used to display changed recipes
editMode = true
#Enables a shortcut button in the pause menu to the list of changed recipes
listButton = true
#Enables a small indicator for all recipes by CraftTweaker (= Exported Recipe changes). This can be used to indicate changes to players after you are done editing
customRecipeIndicator = true

[editing]
	#Disables collapsing tags with one item into the item itself while editing recipes (In Emi)
	noTagCollapsing = true
	#Disables tag name translation while editing recipes (In Emi)
	noTagTranslations = true
	#Also disables tag collapsing and translations outside the recipe editing screen if their options are enabled
	showTagsEverywhere = false
	#Disables the edit mode warning message
	noWarning = true
	#Shows a toast when saving recipe changes
	saveToast = false
