version = 1
enableSodiumMenu = true
cloudCulling = false
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
createfood = true
framedblocks = true
everycomp = true
generatorgalore = true
farmersdelight = true
create_new_age = true
createtransmission = true
create_factory_logistics = true
luckysshowcase = true
tflostblocks = true
extra_gauges = true
adchimneys = true
toms_trading_network = true
easymagic = true
redstonepen = true
etched = true
easyanvils = true
aether_enhanced_extinguishing = true
copycats = true
stonezone = true
veggiesdelight = true
dramaticdoors = true
comforts = true
chalk = true
create_enchantment_industry = true
fastpaintings = true
aether = true
escalated = true
bellsandwhistles = true
amendments = true
mynethersdelight = true
advancementframes = true
permanentsponges = true
moonlight = true
biomesoplenty = true
sophisticatedbackpacks = true
enchanted = true
exposure = true
twilightdelight = true
enderscape = true
endersdelight = true
supplementaries = true
create_vibrant_vaults = true
suppsquared = true
bedspreads = true
chipped = true
petrolpark = true
create = true
culturaldelights = true
buildinggadgets2 = true
interiors = true
dn = true
minecraft = true
undergarden = true
scriptor = true
create_dragons_plus = true
unusual_furniture = true
create_connected = true
elevatorid = true
createdeco = true
trading_floor = true
heads = true
createaddition = true
sophisticatedstorage = true
twilightforest = true
undergardendelight = true
sweety_archaeology = true
petrolsparts = true
crittersandcompanions = true
immersiveengineering = true
aethersdelight = true
toms_storage = true
illagerinvasion = true
expandeddelight = true
