# Use Cloth Config mod for the descriptions.
---
snowGravity: true
snowMakingIce: true
snowAlwaysReplaceable: true
thinnerBoundingBox: true
snowNeverMelt: false
snowSpawnMaxLightLevel: 13
snowPersistMaxLightLevel: 13
snowReduceFallDamage: false
sustainGrassIfLayerMoreThanOne: true
sneakSnowball: false
fancySnowOnUpperSlab: true
rightClickToggleFancySnow: true
mobSpawningMaxLayers: 8
snow-cover:
  restoreOriginalBlocks: false
  replaceWorldgenFeature: true
  placeSnowOnBlock: true
  placeNaturally: true
accumulation:
  naturalMelting: true
  smoothAccumulation: true
  snowAndIceMeltInWarmBiomes: false
  maxLayers: 6
  accumulatesDuringSnowstorm: false
  accumulatesDuringSnowfall: false
integration:
  accumulationWinterOnly: false
debug:
  forceVanillaIceSnowLogic: false
  mobSpawningCommand: false
