# Don't change this! Version used to track needed updates.
version = 1
slotMode = "DEFAULT_SLOT_NO_COPY"
hideDebugInfoInSurvival = true

[accessorySettings]
clockAccessory = true
compassAccessory = true
recoveryCompassAccessory = true
calendarAccessory = true
elytraAccessory = false
spyglassAccessory = true
lanternAccessory = true
totemOfUndyingAccessory = false
enderChestAccessory = false
shulkerBoxAccessory = false
arrowAccessory = false

[infoOverlaySettings]
showYCoordinate = true
obfuscateCompassIfNotOverworld = false
obfuscateClockIfNotOverworld = true
useObfuscationEffect = true

[infoOverlaySettings.overlayFields]
coordinates = true
direction = true
biome = false
dayAndTime = true
weather = true
moonPhase = true
season = true
lastDeathLocation = true