LootJS.modifiers(e => {    
    // e.removeGlobalModifiers(/farmersdelight:.*/)
    // return
    e.removeGlobalModifiers(/farmersdelight:add_loot_abandoned_mineshaft/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_bastion_hoglin_stable/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_bastion_treasure/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_end_city_treasure/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_pillager_outpost/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_ruined_portal/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_shipwreck_supply/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_simple_dungeon/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_village_butcher/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_village_plains_house/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_village_taiga_house/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_village_snowy_house/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_village_desert_house/)
    e.removeGlobalModifiers(/farmersdelight:add_loot_village_savanna_house/)
})