LootJS.modifiers(e => {    
    // e.removeGlobalModifiers(/artifacts:.*/)
    // return
    // e.removeGlobalModifiers(/artifacts:inject.entities.cow/)
    // e.removeGlobalModifiers(/artifacts:inject.entities.mooshroom/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_desert_house/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_plains_house/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_savanna_house/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_snowy_house/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_taiga_house/)
    // e.removeGlobalModifiers(/artifacts:inject.chests.spawn_bonus_chest/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_armorer/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_butcher/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_tannery/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_temple/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_toolsmith/)
    e.removeGlobalModifiers(/artifacts:inject.chests.village.village_weaponsmith/)
    e.removeGlobalModifiers(/artifacts:inject.chests.abandoned_mineshaft/)
    e.removeGlobalModifiers(/artifacts:inject.chests.bastion_hoglin_stable/)
    e.removeGlobalModifiers(/artifacts:inject.chests.bastion_treasure/)
    e.removeGlobalModifiers(/artifacts:inject.chests.buried_treasure/)
    e.removeGlobalModifiers(/artifacts:inject.chests.desert_pyramid/)
    e.removeGlobalModifiers(/artifacts:inject.chests.end_city_treasure/)
    e.removeGlobalModifiers(/artifacts:inject.chests.jungle_temple/)
    e.removeGlobalModifiers(/artifacts:inject.chests.nether_bridge/)
    e.removeGlobalModifiers(/artifacts:inject.chests.pillager_outpost/)
    e.removeGlobalModifiers(/artifacts:inject.chests.ruined_portal/)
    e.removeGlobalModifiers(/artifacts:inject.chests.shipwreck_treasure/)
    e.removeGlobalModifiers(/artifacts:inject.chests.simple_dungeon/)
    e.removeGlobalModifiers(/artifacts:inject.chests.stronghold_corridor/)
    e.removeGlobalModifiers(/artifacts:inject.chests.underwater_ruin_big/)
    e.removeGlobalModifiers(/artifacts:inject.chests.woodland_mansion/)
    e.removeGlobalModifiers(/artifacts:inject.chests.igloo_chest/)
    e.removeGlobalModifiers(/artifacts:inject.chests.ancient_city_ice_box/)
    e.removeGlobalModifiers(/artifacts:inject.chests.ancient_city/)
    e.removeGlobalModifiers(/artifacts:inject.archaeology.desert_pyramid/)
    // e.removeGlobalModifiers(/artifacts:inject.archaeology.desert_well/)
    e.removeGlobalModifiers(/artifacts:inject.archaeology.ocean_ruin_cold/)
    e.removeGlobalModifiers(/artifacts:inject.archaeology.ocean_ruin_warm/)
    // e.removeGlobalModifiers(/artifacts:inject.archaeology.trail_ruins_rare/)
})